steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
      nodejsMirror: 'https://npmmirror.com/mirrors/node'
    displayName: 'Install Node.js'
  - script: |
      node -v
      npm -v
    displayName: 'Verify Node.js and NPM Version'
