parameters:
  - name: appname
    type: string
  - name: context
    type: string
  - name: branchname
    type: string
  - name: authtoken
    type: string
  - name: environment
    type: string
  - name: customEnvironment
    type: string
  - name: customEnvironmentAlias
    type: string
  - name: environmentVariables
    type: string
  - name: customEnvironmentVariables
    type: string

steps:
  - checkout: self
  - template: ../steps/install-node.yml
  - script: |
      npm install
      netlify link --filter=${{ parameters.appname }} --name=${{ parameters.appname }}
      branch=${{ parameters.branchname }}

      if [ ${{ parameters.environment }} = "custom" ]; then
        echo "Custom environment selected"
        echo "Custom environment alias: ${{ parameters.customEnvironmentAlias }}, stripping out any whitespace"
        environmentAlias=$(echo "${{ parameters.customEnvironmentAlias }}" | tr -d '[:space:]')
        echo "Getting environment variables"
        if [ "${{ parameters.environmentVariables }}" = "test" ] || \
           [ "${{ parameters.environmentVariables }}" = "staging" ]; then
          echo "Fetching branch specific environment variables for ${{ parameters.environment }}"
          env_vars_json=$(netlify env:list --json --filter=${{ parameters.appname }} --context=branch:${{ parameters.environment }})
        else
          echo "Fetching context specific environment variables for context ${{ parameters.environmentVariables }}"
          env_vars_json=$(netlify env:list --json --filter=${{ parameters.appname }} --context=${{ parameters.environmentVariables }})
        fi
      else
        echo "Standard environment selected: ${{ parameters.environment }}"
        if [ "${{ parameters.environmentVariables }}" = "Match environment" ] || \
           [ "${{ parameters.environmentVariables }}" = "test" ] || \
           [ "${{ parameters.environmentVariables }}" = "staging" ]; then
          echo "Standard environment variables selected:  ${{ parameters.environmentVariables }}"
          env_vars_json=$(netlify env:list --json --filter=${{ parameters.appname }} --context=branch:${{ parameters.environment }})
        else
          echo "Non-standard environment variables selected: ${{ parameters.environmentVariables }}"
          echo "Fetching ${{ parameters.environmentVariables }} environment variables to use in the ${{ parameters.environment }} deployment"
          env_vars_json=$(netlify env:list --json --filter=${{ parameters.appname }} --context=${{ parameters.environmentVariables }})
        fi
      fi

      echo "Setting build specific environment variables as branch-deploy context which will be used for this build"
      echo "$env_vars_json" | jq -r 'to_entries | .[] | "\(.key): \(.value)"' | while IFS=: read -r key value; do
        if [[ -z "$value" ]]; then
          echo "Error: Value empty for $key"
          exit 1
        else
          echo "Setting variable $key"
          netlify env:set $key $value --context ${{ parameters.context }} --filter ${{ parameters.appname }} > /dev/null 2>&1
        fi
      done

      echo "Setting custom environment variables if provided"
      if [ -n "${{ parameters.customEnvironmentVariables }}" ]; then
        echo "Custom environment variables provided"
        IFS=',' read -ra PAIRS <<< "${{ parameters.customEnvironmentVariables }}"
        for pair in "${PAIRS[@]}"; do
          key="${pair%%=*}"
          value="${pair#*=}"
          if [[ -z "$value" ]]; then
            echo "Error: Value empty for $key"
            exit 1
          else
            echo "Setting custom variable $key"
            netlify env:set $key $value --context ${{ parameters.context }} --filter ${{ parameters.appname }} > /dev/null 2>&1
          fi
        done
      else
        echo "No custom environment variables provided"
      fi

      echo "Deploying"
      if [ "${{ parameters.customEnvironment }}" = "true" ]; then
        echo "Deploying to custom alias $environmentAlias"
        netlify deploy --filter=${{ parameters.appname }} --context=${{ parameters.context }} --auth=${{ parameters.authtoken }} --alias $environmentAlias
      else
        echo "Deploying ${{ parameters.appname }} to ${{ parameters.environment }}"
        netlify deploy --filter=${{ parameters.appname }} --context=${{ parameters.context }} --auth=${{ parameters.authtoken }} --alias ${{ parameters.environment }}
      fi

      echo "Cleaning up custom environment variables if provided"
      if [ -n "${{ parameters.customEnvironmentVariables }}" ]; then
        echo "Custom environment variables provided, deleting them"
        IFS=',' read -ra PAIRS <<< "${{ parameters.customEnvironmentVariables }}"
        for pair in "${PAIRS[@]}"; do
          key="${pair%%=*}"
          value="${pair#*=}"
          echo "Deleting custom variable $key"
          netlify env:unset $key --context ${{ parameters.context }} --filter ${{ parameters.appname }}
        done
      else
        echo "No custom environment variables to delete"
      fi

    displayName: 'Deploy ${{ parameters.appname }}'
