trigger: none
name: Clean abandoned PRs and Review envs

parameters:
- name: resourceGroups
  type: object
  default:
  - mapsnextjs-test-uksouth-rg
  - pensionwise-review-uksouth-rg
  - mapsnextjs-review-uksouth-rg

schedules:
- cron: '0 20 * * 1,3,5'
  always: true
  branches:
    include:
    - main
  batch: true
  displayName: PR Cleanup

jobs:
- job: CleanupPRs
  displayName: 'Clean up Pull Requests'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      set -e
      echo "Fetching abandoned PRs..."
      response=$(curl -s -u :$(ACCESS-TOKEN) "https://dev.azure.com/moneyandpensionsservice/MaPS%20Digital/_apis/git/repositories/maps-apps/pullrequests?searchCriteria.status=abandoned&api-version=7.1" -H "Accept: application/json")
      echo "API Response: $response"
      pr_ids=$(echo $response | jq -r '.value[] | .pullRequestId | tostring')
      if [ -z "$pr_ids" ]; then
        echo "No abandoned PRs found."
        exit 0
      fi
      echo "Abandoned PRs: $pr_ids"
      echo "##vso[task.setvariable variable=pr_id_list;isOutput=true]$pr_ids"
    name: getPRs
    displayName: Get PRs

  - ${{ each resourcegroup in parameters.resourceGroups }}:
    - template: templates/jobs/clean-env-prs.yml
      parameters:
        resourcegroup: ${{ resourcegroup }}
        pr_id_list: $(getPRs.pr_id_list)