trigger: none
name: Github Sync

schedules:
  - cron: '0 9 * * 1' # Run at 9am every Monday
    displayName: Weekly Monday run
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git config --global user.email $(user-email)
      git config --global user.name $(user-name)
      git config --global init.defaultBranch main
      git clone https://moneyandpensionsservice@dev.azure.com/moneyandpensionsservice/MaPS%20Digital/_git/maps-apps
      rm -rf .git
      git init
      git branch -M main
      git add -f .
      git commit -am 'Clean repo'
      git push -f https://$(personal-access-token)@github.com/moneyadviceservice/maps-apps.git main
    displayName: 'Clean repo and push to Github'
