trigger: none
name: Github synch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git config --global user.email "AutoSVCACC@mapsorg.onmicrosoft.com"
      git config --global user.name "AutoSVCACC"
      git config --global init.defaultBranch main
      git clone https://moneyandpensionsservice@dev.azure.com/moneyandpensionsservice/MaPS%20Digital/_git/maps-apps
      rm -rf .git
      git init
      git branch -M main
      git add -f .
      git commit -am 'Clean repo'
      git push -f https://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@github.com/moneyadviceservice/maps-apps.git main
    displayName: 'Clean repo and push to Github'
