import { FlowName, StepName } from '../lib/constants';

// Define route flows
export const routeFlow = new Map<string, string[]>([
  [
    FlowName.DEFAULT,
    [
      StepName.ENQUIRY_TYPE,
      StepName.ABOUT_MONEY_MANAGEMENT,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.SCAMS,
    [
      StepName.ENQUIRY_TYPE,
      StepName.ABOUT_SCAMS,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.DEBT_ADVICE,
    [
      StepName.ENQUIRY_TYPE,
      StepName.ABOUT_DEBT,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.INSURANCE,
    [StepName.ENQUIRY_TYPE, StepName.INSURANCE_TYPE] as StepName[],
  ],
  [
    FlowName.INSURANCE_OTHER,
    [
      StepName.ENQUIRY_TYPE,
      StepName.INSURANCE_TYPE,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.INSURANCE_TRAVEL,
    [
      StepName.ENQUIRY_TYPE,
      StepName.INSURANCE_TYPE,
      StepName.ABOUT_INSURANCE,
    ] as StepName[],
  ],
  [
    FlowName.PENSIONS_AND_RETIREMENT,
    [StepName.ENQUIRY_TYPE, StepName.PENSION_TYPE] as StepName[],
  ],
  [
    FlowName.PENSIONS_STATE_PENSION,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.ABOUT_STATE_PENSION,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.PENSIONS_TRACING,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.ABOUT_PENSION_TRACING,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.MHPD,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.ABOUT_MHPD,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.PENSIONS_APPOINTMENTS,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.APPOINTMENT_TYPE,
    ] as StepName[],
  ],
  [
    FlowName.APPOINTMENT_PENSION_WISE,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.APPOINTMENT_TYPE,
      StepName.ABOUT_PENSION_WISE,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.APPOINTMENT_DIVORCE,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.APPOINTMENT_TYPE,
      StepName.ABOUT_PENSION_DIVORCE,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
  [
    FlowName.PENSIONS_GUIDANCE,
    [
      StepName.ENQUIRY_TYPE,
      StepName.PENSION_TYPE,
      StepName.NAME,
      StepName.DATE_OF_BIRTH,
      StepName.CONTACT_DETAILS,
      StepName.ENQUIRY,
      StepName.LOADING,
      StepName.CONFIRMATION,
    ] as StepName[],
  ],
]);
