[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    base = "/"
    command = "npx nx run sdlt-calculator:serve"
    targetPort = 4396
    autoLaunch = false

