import { ClassificationMatrix } from '../classificationMatrix';

/**
 * When creating a classification matrix.
 * The top/first set of keys are the left column keys,
 * in this case, the accrued value unavailable code.
 *
 * So like reading a book left to right, starts at the top left
 * finishes on the bottom right.
 */
export const dcClassificationMatrix = new ClassificationMatrix({
  None: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  ANO: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  DBC: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  DCC: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  MEM: {
    None: 'RED',
    ANO: 'RED',
    DB: 'RED',
    DBC: 'RED',
    DCC: 'RED',
    DCHA: 'RED',
    DCHP: 'RED',
    MEM: 'RED',
    NET: 'RED',
    NEW: 'RED',
    PPF: 'RED',
    TRN: 'RED',
    WU: 'RED',
  },
  NET: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  NEW: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  PPF: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  TRN: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
  WU: {
    None: 'GREEN',
    ANO: 'GREEN',
    DB: 'GREEN',
    DBC: 'GREEN',
    DCC: 'GREEN',
    DCHA: 'GREEN',
    DCHP: 'GREEN',
    MEM: 'RED',
    NET: 'GREEN',
    NEW: 'GREEN',
    PPF: 'GREEN',
    TRN: 'GREEN',
    WU: 'GREEN',
  },
});
