[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/cash-in-chunks package.json libs/shared"

[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    base = "/"
    command = "npx nx run cash-in-chunks:serve"
    targetPort = 4307
    autoLaunch = false
