[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/salary-calculator package.json libs/shared"

[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    base = "/"
    command = "npx nx run salary-calculator:serve"
    targetPort = 4390
    autoLaunch = false
