[[context.production.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.deploy-preview.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[[context.develop.plugins]]
    package = "/netlify/tools/plugins/stop-build"

[dev]
    base = "/"
    command = "npx nx run budget-planner:serve"
    targetPort = 4350

[functions]
  included_files = ["apps/budget-planner/public/assets/*.xlsx"]
